services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CORS_ALLOWED_ORIGINS=http://frontend,http://localhost,http://localhost:5173
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
